development:
  mail_user_name: 'foobar'
  mail_password: 'S!551c4@n'
  domain: "localhost"

stage:
  mail_user_name: 'sissichan@rails.sissichan.com'
  mail_password: 'S!551c4@n'
  domain: "rails.sissichan.com"

production:
  mail_user_name: 'sissichan@rails.sissichan.com'
  mail_password: 'S!551c4@n'
  domain: "sissichan.com"
